### ISSUE TITLE
从goploy安装agent出问题 

### ISSUE THREAD

**Issue by figureout** [goploy-devops/goploy-agent#1]
发现好像是wget 和curl下载没有重定向到/dev/null 会影响后面的执行，我把
downloadCommand := fmt.Sprintf("wget -N %s", downloadURL)
改成
	downloadCommand := fmt.Sprintf("wget  %s --connect-timeout=7 --dns-timeout=7 -nv -O goploy-agent >> /dev/null 2>&1", downloadURL)

**Comment by zhenorzz** [comment]
好的我试试
