### ISSUE TITLE
虚拟机x86 linux启动agent失败

### ISSUE THREAD

**Issue by lizhian** [goploy-devops/goploy-agent#2]
启动失败,服务器为运行在虚拟机的x86 linux,agent版本为1.3.1

[root@bg01 goploy-agent]# cat /proc/version
Linux version 5.4.244-1.el7.elrepo.x86_64 (mockbuild@Build64R7) (gcc version 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC)) #1 SMP Tue May 30 18:30:47 EDT 2023

[root@bg01 goploy-agent]# pwd
/opt/goploy-agent

[root@bg01 goploy-agent]# ll
总用量 16620
-rwxr-xr-x 1 root root 17014650 4月  29 2022 goploy-agent
-rw-r--r-- 1 root root      184 8月   1 15:56 goploy-agent.toml

[root@bg01 goploy-agent]# cat goploy-agent.toml 
env = production
[goploy]
reportURL = http://192.168.2.181:4121
key = 2023-08-01 15:03:59.874186792 +0800 CST m=+0.003147093
uidType = id
uid = 1
[log]
path = stdout
[web]
port = 4122

[root@bg01 goploy-agent]# ./goploy-agent 

   ______            __           
  / ____/___  ____  / /___  __  __
 / / __/ __ \/ __ \/ / __ \/ / / /
/ /_/ / /_/ / /_/ / / /_/ / /_/ / 
\____/\____/ .___/_/\____/\__, /  
          /_/            /____/   1.3.1

The configuration file already exists, no need to reinstall (if you need to reinstall, please delete the .env file, then restart.)
panic: toml: incomplete number

goroutine 1 [running]:
github.com/zhenorzz/goploy-agent/config.Create(0xc00001a1e0, 0x23)
        D:/Users/Administrator/docker-env/project/go/goploy-agent/config/Config.go:40 +0xc5
main.main()
        D:/Users/Administrator/docker-env/project/go/goploy-agent/main.go:66 +0xdd
[root@bg01 goploy-agent]#

**Comment by zhenorzz** [comment]
panic: toml: incomplete number (格式不对，key是字符串，你少了引号)
key = 2023-08-01 15:03:59.874186792 +0800 CST m=+0.003147093
key = '2023-08-01 15:03:59.874186792 +0800 CST m=+0.003147093'

**Comment by lizhian** [comment]
已成功启动,感谢
goploy-agent.toml是在goploy页面上点击'安装agent'按钮自动生成的
agent安装脚本可能还需要改一下

**Comment by zhenorzz** [comment]
好的好的
